/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Materials': RouteRecordInfo<'/Materials', '/Materials', Record<never, never>, Record<never, never>>,
    '/MaterialsDetails': RouteRecordInfo<'/MaterialsDetails', '/MaterialsDetails', Record<never, never>, Record<never, never>>,
    '/OrderDetails': RouteRecordInfo<'/OrderDetails', '/OrderDetails', Record<never, never>, Record<never, never>>,
    '/Orders': RouteRecordInfo<'/Orders', '/Orders', Record<never, never>, Record<never, never>>,
  }
}
